### ISSUE TITLE
This package does not install correctly on windows npm

### ISSUE THREAD

**Issue by aceslick911** [Stewart-Taylor/Node-TestRail#63]
I get this error:
1878 error Windows_NT 10.0.10240
1879 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\angelo.perera\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-testrail" "--save-dev"
1880 error node v5.2.0
1881 error npm  v3.7.2
1882 error code ELIFECYCLE
1883 error node-testrail@0.0.6 install: `coffee -o lib -c src/testrail.coffee`
1883 error Exit status 1
1884 error Failed at the node-testrail@0.0.6 install script 'coffee -o lib -c src/testrail.coffee'.
1884 error Make sure you have the latest version of node.js and npm installed.
1884 error If you do, this is most likely a problem with the node-testrail package,
1884 error not with npm itself.
1884 error Tell the author that this fails on your system:
1884 error     coffee -o lib -c src/testrail.coffee
1884 error You can get information on how to open an issue for this project with:
1884 error     npm bugs node-testrail
1884 error Or if that isn't available, you can get their info via:
1884 error     npm owner ls node-testrail
1884 error There is likely additional logging output above.
1885 verbose exit [ 1, true ]

I tried to npm install -g coffee-script incase because it looks like it's trying to execute "coffee ..." but that didn't work either.

Do you have a version of this that doesn't require coffee installed? A JS only version?

**Comment by Stewart-Taylor** [comment]
I will look into what is causing the javascript version not to build.

**Comment by Stewart-Taylor** [comment]
Removed the coffeescript dependency from the install script. The compiled javascript version is now published to npm. This should solve your problem and make the module a bit more lightweight.
